// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TodoApp$ReactHooksTemplate = require("./TodoApp.bs.js");

((require('./myStyles.css')));

ReactDOMRe.renderToElementWithId(React.createElement(TodoApp$ReactHooksTemplate.make, {
          title: "Todo App"
        }), "root");

/*  Not a pure module */
